name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Gemini 2.0 Flash
    provider: gemini
    model: gemini-2.0-flash
    apiKey: {GeminiAPIKEYHERE}
  - name: Gemini 2.0 Flash Lite
    provider: gemini
    model: gemini-2.0-flash-lite
    apiKey: {GeminiAPIKEYHERE}
  - name: Gemini 2.5 Pro Experimental
    provider: gemini
    model: gemini-2.5-pro-exp-03-25
    apiKey: {GeminiAPIKEYHERE}
  - name: Gemini 1.5 Pro
    provider: gemini
    model: gemini-1.5-pro-latest
    apiKey: {GeminiAPIKEYHERE}
  - name: Gemini 1.5 Flash
    provider: gemini
    model: gemini-1.5-flash-latest
    apiKey: {GeminiAPIKEYHERE}
  - name: Autodetect
    provider: ollama
    model: AUTODETECT
  - name: GPT-3.5-Turbo
    provider: openai
    model: gpt-3.5-turbo
    apiKey: {GPT_APIKEY}
context:
  - provider: codebase
  - provider: http
    params:
      url: http://localhost:8000/context
      title: JSS_Context_Server
      displayTitle: Sitecore JSS Context Server
      description: Provides Sitecore JSS project context via a local HTTP server
